[Narwhal] introduce consensus randomized tests (#9239)
## Description 

This PR is introducing "randomised" tests for our consensus engine. A
main test has been added `bullshark_randomised_tests` where the test
orchestration is taking place. Basically the test is running for
multiple core properties (ex various DAG rounds, gc_depth, committee
size) where for each test iteration it:
* `creates random DAGs` based on some quality characteristics
(`FailureModes`)
* `creates multiple execution plans` - different order of feeding the
certificates to consensus - using a variation of [Kahn's
algorithm](https://en.wikipedia.org/wiki/Topological_sorting), and
executes those via the Bullshark consensus engine
* `compares the output of each execution plan` to ensure they don't
diverge - for the same DAG we should expect to have the exact same
output for different execution plans

All the random generators used across the above process are seeded by
known seeds - and printed on informative output - so we can later easily
reproduce a scenario in case of a failure.

The test will run as part of the nightly CI workflow, as it can take
quite some time to execute. Also, I have added some finger in the air
parameters for the time being, but we can tune them further based on run
time etc.

The DAG generation and the execution plan creation is using (seeded)
randomness in order to achieve various permutations - which of course is
not exhaustive and the different combinations depend to the number of
iterations. To reproduce an error someone can use the provided seeds to
replay the specific scenario.

### Running the tests manually
To run the tests manually can do via the nextest:
```
 cargo nextest run -p narwhal-consensus bullshark_randomised_tests --run-ignored ignored-only --no-capture
```

If a failure is detected then a log line like the following will be
printed:
```
Fork detected in plans for run_id=7, seed=18, rounds=7, committee=4, gc_depth=7, modes=FailureModes { nodes_failure_probability: 0.0, slow_nodes_percentage: 0.33, slow_nodes_failure_probability: 0.7 }'
```

Then the `run_id` can be used to go back to the
`bullshark_randomised_tests`, set it to that number and run the test ,
so can reproduce the result and investigate.

### Running against "fork" bug
As part of https://github.com/MystenLabs/sui/pull/8403 we fixed a fork
bug that got introduced in earlier work. When running the randomised
tests against the code with the bug managers to successfully detect the
fork and report it. To test this I cherry picked the randomised test on
top the commit with the issue and ran the tests. The branch can be
[found on this
branch](https://github.com/MystenLabs/sui/blob/577e722b96925e9161a6d5522ae6024fd937ba3b/narwhal/consensus/src/tests/randomized_tests.rs#L66)
.

Running like this:
```
 cargo nextest run -p narwhal-consensus bullshark_randomised_tests --run-ignored ignored-only --no-capture
```

will output:

```
thread 'bullshark::randomized_tests::bullshark_randomised_tests' panicked at 'assertion failed: `(left == right)`
  left: `[dwwml/yqkhsUT8G7: C1(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, eKp5YZF6ApG6lTS9, E0), XwSoL1Tx0XzPywRx: C1(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, RTmx44i8TAq6UJrn, E0), IerZdSvQBNXmie6x: C1(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, OcqdgfvXy0lsqb4p, E0), 0bNKLmBEzcgw+pbR: C2(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, wZtJ2NyeHrAKU7PF, E0), jC8y2AbMI2GMF56d: C1(hsHWobFaIM1WzZYy+mgfv7ABPS0G10Wf2iAWd/xmOla/oarahIEHvNlxCoOnrbteE3O7wsVFwl0HPBZvGCRbdemwudJk1xcPfEc7R9rGmWPP3lkogbw2QK/MVrg2spqG, uvP+CGnDrCSqi4ZP, E0), 1oPpAISn93H9n9ao: C2(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, zVms6gWDMBzVG/Xm, E0), yZ400cpb93I9TnzX: C2(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, TtlXcRyUU2u0+eDQ, E0), 75QIn5xjThJarMUM: C3(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, yUZRIIA32ljxlifT, E0), k2Zqd75XK7Onak9o: C3(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, L1zUn/wKugYLV+Xv, E0), JzxeOnfWcbpAQcts: C3(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, 5ZyjwRmHNMmAOZ/L, E0), fPAjkOz5Tt+mxOZC: C4(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, vJWr4dIDXo0F30Vl, E0), TL8Kydc5sdhSxnP/: C3(hsHWobFaIM1WzZYy+mgfv7ABPS0G10Wf2iAWd/xmOla/oarahIEHvNlxCoOnrbteE3O7wsVFwl0HPBZvGCRbdemwudJk1xcPfEc7R9rGmWPP3lkogbw2QK/MVrg2spqG, fSYvLRNdKrQhcCp+, E0), yMpRyHGQo2cGi/tv: C4(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, ME1XmO723pJhuSqt, E0), ltALm4ODvtotkhyC: C4(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, s80s5UMIrXpXbkXK, E0), nSH6bchZOV93PJho: C4(hsHWobFaIM1WzZYy+mgfv7ABPS0G10Wf2iAWd/xmOla/oarahIEHvNlxCoOnrbteE3O7wsVFwl0HPBZvGCRbdemwudJk1xcPfEc7R9rGmWPP3lkogbw2QK/MVrg2spqG, p4EPG6LVG3S32DMW, E0), f2iy8HuuaxfcspQY: C5(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, cIDSU9Bg3xMrDA4V, E0), fTRna0aA8xNa6N0O: C5(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, sbD8udPdVTQooLuG, E0), HtGRM6uo63WTNzzz: C5(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, rXqqkKkUMUkpmbGJ, E0), rem1TN11AkWXsqaq: C6(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, mXOWLEy6W0f4XGtk, E0)]`,
 right: `[dwwml/yqkhsUT8G7: C1(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, eKp5YZF6ApG6lTS9, E0), XwSoL1Tx0XzPywRx: C1(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, RTmx44i8TAq6UJrn, E0), IerZdSvQBNXmie6x: C1(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, OcqdgfvXy0lsqb4p, E0), 0bNKLmBEzcgw+pbR: C2(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, wZtJ2NyeHrAKU7PF, E0), jC8y2AbMI2GMF56d: C1(hsHWobFaIM1WzZYy+mgfv7ABPS0G10Wf2iAWd/xmOla/oarahIEHvNlxCoOnrbteE3O7wsVFwl0HPBZvGCRbdemwudJk1xcPfEc7R9rGmWPP3lkogbw2QK/MVrg2spqG, uvP+CGnDrCSqi4ZP, E0), 1oPpAISn93H9n9ao: C2(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, zVms6gWDMBzVG/Xm, E0), yZ400cpb93I9TnzX: C2(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, TtlXcRyUU2u0+eDQ, E0), 75QIn5xjThJarMUM: C3(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, yUZRIIA32ljxlifT, E0), k2Zqd75XK7Onak9o: C3(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, L1zUn/wKugYLV+Xv, E0), JzxeOnfWcbpAQcts: C3(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, 5ZyjwRmHNMmAOZ/L, E0), fPAjkOz5Tt+mxOZC: C4(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, vJWr4dIDXo0F30Vl, E0), n5mpACbbClwrs3OK: C2(hsHWobFaIM1WzZYy+mgfv7ABPS0G10Wf2iAWd/xmOla/oarahIEHvNlxCoOnrbteE3O7wsVFwl0HPBZvGCRbdemwudJk1xcPfEc7R9rGmWPP3lkogbw2QK/MVrg2spqG, MeOvYaDWid+gWdAA, E0), TL8Kydc5sdhSxnP/: C3(hsHWobFaIM1WzZYy+mgfv7ABPS0G10Wf2iAWd/xmOla/oarahIEHvNlxCoOnrbteE3O7wsVFwl0HPBZvGCRbdemwudJk1xcPfEc7R9rGmWPP3lkogbw2QK/MVrg2spqG, fSYvLRNdKrQhcCp+, E0), yMpRyHGQo2cGi/tv: C4(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, ME1XmO723pJhuSqt, E0), ltALm4ODvtotkhyC: C4(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, s80s5UMIrXpXbkXK, E0), nSH6bchZOV93PJho: C4(hsHWobFaIM1WzZYy+mgfv7ABPS0G10Wf2iAWd/xmOla/oarahIEHvNlxCoOnrbteE3O7wsVFwl0HPBZvGCRbdemwudJk1xcPfEc7R9rGmWPP3lkogbw2QK/MVrg2spqG, p4EPG6LVG3S32DMW, E0), f2iy8HuuaxfcspQY: C5(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, cIDSU9Bg3xMrDA4V, E0), fTRna0aA8xNa6N0O: C5(qFHWDpkBDWYzUPieD7zvu6vT0eTcUEeRmZ7r9Bd6nVSKZN8/VTXOtBF7I6uTNsZgF0sjkxgE6sTv6rHzYYQXhepALY49pCXzAk1bwd30esNmQxTxKnWOIBl/c5dnnINP, sbD8udPdVTQooLuG, E0), HtGRM6uo63WTNzzz: C5(spJhWejffj1vEBGZgKdW972Zvu/4J0xMhJN9MmHAjGcVqE4VwT13lolJZdTgZHANERCqwhOs1+wZBlG3XfqjwDr8ShhIdxG9x/WJBoihhd7wV6mnw4H37TVyfwc+8hFj, rXqqkKkUMUkpmbGJ, E0), rem1TN11AkWXsqaq: C6(gM7/G81TYckTfJAIEkHv5ituvxNqFP9/ENpMq5+fFkzo+gmIP2GIZNcgbrEKm5e8Ay5FulFJESCqFR70Og9i3kMtvtbzkOA1R4nKyXTWuzAzuvJHo2ezl+5eu/LebwKv, mXOWLEy6W0f4XGtk, E0)]`: Fork detected in plans for run_id=7, seed=18, rounds=7, committee=4, gc_depth=7, modes=FailureModes { nodes_failure_probability: 0.0, slow_nodes_percentage: 0.33, slow_nodes_failure_probability: 0.7 }'
```

where one extra certificate gets committed in one case compared to the
other

### Future work
- [ ] Parallelise test runs
- [ ] pretify DAG output and improve the reporting to allow easier
debugging
- [ ] add more properties on DAG generator to support more cases
- [ ] currently works when authority per stake = 1, change tests to
support variable stakes

## Test Plan 


---
If your changes are not user-facing and not a breaking change, you can
skip the following section. Otherwise, please indicate what changed, and
then add to the Release Notes section as highlighted during the release
process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade
binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes