chore: update nexlint (MystenLabs/mysten-infra#183)
This updates nexlint in order to pick up a dependency update in guppy, in order to fix errors that are cropping up in ci:

```
Error: while building package graph

Caused by:
    failed to construct package graph: for package 'windows-sys 0.42.0 (registry+https://github.com/rust-lang/crates.io-index)': for dependency 'windows_aarch64_gnullvm', parsing target 'aarch64-pc-windows-gnullvm' failed: unknown target triple
```