[indexer] Integrate indexer into sui-test-validator (#9541)
## Description 

[sui-test-validator](https://docs.sui.io/build/sui-local-network) starts
a local network that includes a Sui Full node, a Sui validator, and a
Sui faucet. With this PR, it now starts an indexer as well. This assumes
that Postgres is running locally. This allows app builders to test out
their applications against indexer locally in a single step.

By default, the indexer will not run unless `--with-indexer true` is
specified. Like fullnode, the postgres db will be reset upon restart.

## Follow up
- config which route uses the indexer db
- handle errors when postgres is not running. Right now it will panic
with the error message `thread 'main' panicked at 'called
`Result::unwrap()` on an `Err` value: PgConnectionPoolInitError("Failed
to initialize connection pool with error: Error(Some(\"connection to
server at \\\"localhost\\\" (::1), port 5432 failed`
- Figure out data persistence upon restart
- Update docs once enough people dogfood it


## Test Plan 

0. Make sure postgres db is running
1. start `sui-test-validator`
```
RUST_LOG="consensus=off" ./target/debug/sui-test-validator --with-indexer true
Fullnode RPC URL: http://127.0.0.1:9000
Indexer RPC URL: 127.0.0.1:9124
Faucet URL: http://127.0.0.1:9123
```
2. send a request to indexer rpc

```
curl --location --request POST 'http://127.0.0.1:9124' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "sui_getTotalTransactionNumber",
  "params": []
}'

{"jsonrpc":"2.0","result":663,"id":1}%  
```