[seed-search.py] make prints threadsafe (#22371)
## Description 
encountered a few errors when running `seed-search.py` locally:
```
"/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/johnmartin/src/github.com/MystenLabs/sui/./scripts/simtest/seed-search.py", line 39, in run_command
    print(f"stdout:\n=========================={stdout.decode('utf-8')}\n==========================")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BlockingIOError: [Errno 35] write could not complete without blocking
Killing child processes
[1]    52777 killed     ./scripts/simtest/seed-search.py --test simtest --
```
```
==========================Traceback (most recent call last):
  File "/Users/johnmartin/src/github.com/MystenLabs/sui/./scripts/simtest/seed-search.py", line 113, in <module>
    main(commands)
    ~~~~^^^^^^^^^^
  File "/Users/johnmartin/src/github.com/MystenLabs/sui/./scripts/simtest/seed-search.py", line 62, in main
    exit_code = future.result()
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
Traceback (most recent call last):
  File "/Users/johnmartin/src/github.com/MystenLabs/sui/./scripts/simtest/seed-search.py", line 113, in <module>
    main(commands)
  File "/Users/johnmartin/src/github.com/MystenLabs/sui/./scripts/simtest/seed-search.py", line 62, in main
    exit_code = future.result()
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
```


## Test plan 

local runs

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to
your changes, release notes aren't required.

For each box you select, include information after the relevant heading
that describes the impact of your changes that a user might notice and
any actions they must take to implement updates.

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK: