[narwhal] Temporarily disable NW Certificate V2 (#14257)
## Description 

- Disabled CertificateV2 temporarily for additional testing
- Removed unused Cert methods
- Fixed an issue where old certificate versions were not being gated
properly and were being accepted by the network and causing panics. This
was happening via the RequestVote missing parents codepath.

```
thread '{"timestamp":"2023-10-13T18:14:52.906206Z","level":"ERROR","fields":{"message":"panicked at narwhal/types/src/primary.rs:1024:9:\nnot implemented: CertificateV2 field! Use aggregated_signature.","panic.file":"narwhal/types/src/primary.rs","panic.line":1024,"panic.column":9},"target":"telemetry_subscribers","filename":"crates/telemetry-subscribers/src/lib.rs","line_number":201}
```