sui branch cut: generate all required PRs (#23282)
## Description 
Generates framework bytecode snapshot and version bump PRs

## Test plan 
Test Plan:
Two PRs were generated with the shell script:
https://github.com/MystenLabs/sui/pull/23286 and
https://github.com/MystenLabs/sui/pull/23287

```
eugene@eugene-dev ~/code/sui/ (ebmifa/gen_branch_cut_prs) $ ./scripts/gen_branch_cut_prs.sh 
Switched to a new branch 'eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809'
   Compiling sui-framework-snapshot v1.56.0 (/home/eugene/code/sui/crates/sui-framework-snapshot)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 8.01s
     Running `target/debug/sui-framework-snapshot`
Staging all changed files...
[eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809 f8d3f845c9] Sui v1.56.0 Framework Bytecode snapshot
 6 files changed, 30 insertions(+)
 create mode 100644 crates/sui-framework-snapshot/bytecode_snapshot/95/0x0000000000000000000000000000000000000000000000000000000000000001
 create mode 100644 crates/sui-framework-snapshot/bytecode_snapshot/95/0x0000000000000000000000000000000000000000000000000000000000000002
 create mode 100644 crates/sui-framework-snapshot/bytecode_snapshot/95/0x0000000000000000000000000000000000000000000000000000000000000003
 create mode 100644 crates/sui-framework-snapshot/bytecode_snapshot/95/0x000000000000000000000000000000000000000000000000000000000000000b
 create mode 100644 crates/sui-framework-snapshot/bytecode_snapshot/95/0x000000000000000000000000000000000000000000000000000000000000dee9
Enumerating objects: 30, done.
Counting objects: 100% (30/30), done.
Delta compression using up to 16 threads
Compressing objects: 100% (24/24), done.
Writing objects: 100% (24/24), 81.22 KiB | 13.54 MiB/s, done.
Total 24 (delta 15), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (15/15), completed with 6 local objects.
remote: 
remote: Create a pull request for 'eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809' on GitHub by visiting:
remote:      https://github.com/MystenLabs/sui/pull/new/eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809
remote: 
remote: GitHub found 73 vulnerabilities on MystenLabs/sui's default branch (5 critical, 11 high, 46 moderate, 11 low). To find out more, visit:
remote:      https://github.com/MystenLabs/sui/security/dependabot
remote: 
To github.com:MystenLabs/sui.git
 * [new branch]            eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809 -> eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809
Branch 'eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809' set up to track remote branch 'eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809' from 'origin'.
Pull request for Sui v1.56.0 Framework Bytecode snapshot created: https://github.com/MystenLabs/sui/pull/23286
✓ Pull request MystenLabs/sui#23286 will be automatically merged via squash when all requirements are met
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
From github.com:MystenLabs/sui
 * branch                  main       -> FETCH_HEAD
Already up to date.
Switched to a new branch 'eugene/sui-v1.57.0-version-bump-20250825164809'
    Updating crates.io index
    Checking sui-sdk v1.57.0 (/home/eugene/code/sui/crates/sui-sdk)
    Checking sui-move-natives-latest v0.1.0 (/home/eugene/code/sui/sui-execution/latest/sui-move-natives)
    Checking sui-data-ingestion-core v0.1.0 (/home/eugene/code/sui/crates/sui-data-ingestion-core)
   Compiling sui-package-management v1.57.0 (/home/eugene/code/sui/crates/sui-package-management)
    Checking sui-indexer-alt-framework v1.57.0 (/home/eugene/code/sui/crates/sui-indexer-alt-framework)
    Checking sui-proxy v0.0.2 (/home/eugene/code/sui/crates/sui-proxy)
    Checking sui-framework-snapshot v1.57.0 (/home/eugene/code/sui/crates/sui-framework-snapshot)
    Checking sui-storage v0.1.0 (/home/eugene/code/sui/crates/sui-storage)
error[E0433]: failed to resolve: could not find `IdGasParameters` in `type_name`
   --> sui-execution/latest/sui-move-natives/src/lib.rs:849:33
    |
849 |             id: MSN::type_name::IdGasParameters::new(
    |                                 ^^^^^^^^^^^^^^^
    |                                 |
    |                                 could not find `IdGasParameters` in `type_name`
    |                                 help: a struct with a similar name exists: `GasParameters`

error[E0560]: struct `move_stdlib_natives::type_name::GasParameters` has no field named `id`
   --> sui-execution/latest/sui-move-natives/src/lib.rs:849:13
    |
849 |             id: MSN::type_name::IdGasParameters::new(
    |             ^^ `move_stdlib_natives::type_name::GasParameters` does not have this field
    |
    = note: all struct fields are already assigned

    Checking sui-kvstore v1.57.0 (/home/eugene/code/sui/crates/sui-kvstore)
    Checking suins-indexer v1.57.0 (/home/eugene/code/sui/crates/suins-indexer)
    Checking sui-indexer-builder v0.1.0 (/home/eugene/code/sui/crates/sui-indexer-builder)
    Checking sui-faucet v1.57.0 (/home/eugene/code/sui/crates/sui-faucet)
    Checking sui-oracle v1.57.0 (/home/eugene/code/sui/crates/sui-oracle)
    Checking sui-light-client v1.57.0 (/home/eugene/code/sui/crates/sui-light-client)
    Checking sui-rpc-loadgen v1.57.0 (/home/eugene/code/sui/crates/sui-rpc-loadgen)
Some errors have detailed explanations: E0433, E0560.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `sui-move-natives-latest` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Staging all changed files...
[eugene/sui-v1.57.0-version-bump-20250825164809 f26604b6e2] Sui v1.57.0 Version Bump
 3 files changed, 58 insertions(+), 58 deletions(-)
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 16 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (8/8), 1.41 KiB | 361.00 KiB/s, done.
Total 8 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
remote: 
remote: Create a pull request for 'eugene/sui-v1.57.0-version-bump-20250825164809' on GitHub by visiting:
remote:      https://github.com/MystenLabs/sui/pull/new/eugene/sui-v1.57.0-version-bump-20250825164809
remote: 
remote: GitHub found 73 vulnerabilities on MystenLabs/sui's default branch (5 critical, 11 high, 46 moderate, 11 low). To find out more, visit:
remote:      https://github.com/MystenLabs/sui/security/dependabot
remote: 
To github.com:MystenLabs/sui.git
 * [new branch]            eugene/sui-v1.57.0-version-bump-20250825164809 -> eugene/sui-v1.57.0-version-bump-20250825164809
Branch 'eugene/sui-v1.57.0-version-bump-20250825164809' set up to track remote branch 'eugene/sui-v1.57.0-version-bump-20250825164809' from 'origin'.
Pull request for Sui v1.57.0 Version Bump created: https://github.com/MystenLabs/sui/pull/23287
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>