Fix clippy warnings due to auto-deref
A typical warning looks like this:
```
error: deref which would be done by auto-deref
  --> sui-execution/latest/sui-move-natives/src/crypto/zklogin.rs:93:9
   |
93 |         &*audience.as_bytes_ref(),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `&audience.as_bytes_ref()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
```