disable pruning of checkpoints during simtests (#23936)
## Description 

attempting to fix missing checkpoint during simtest:
```
reproduce this error
test v2::ledger_service::get_checkpoint::get_checkpoint ... FAILED

failures:

failures:
    v2::ledger_service::get_checkpoint::get_checkpoint

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 116 filtered out; finished in 353.13s


--- STDERR:              sui-e2e-tests::rpc v2::ledger_service::get_checkpoint::get_checkpoint ---

thread '<unnamed>' panicked at crates/sui-e2e-tests/tests/rpc/v2/ledger_service/get_checkpoint.rs:145:10:
called `Result::unwrap()` on an `Err` value: Status { code: Internal, message: "Error { inner: Inner { kind: Custom, source: Some(\"unabled to load object ObjectKey(0x5dfc69dcdc15c0b65efcdad2612b2d37453aaeda297024dc4397db47f8f85bd0, SequenceNumber(1))\") } }", details: b"\x08\r\x12\xb0\x01Error { inner: Inner { kind: Custom, source: Some(\"unabled to load object ObjectKey(0x5dfc69dcdc15c0b65efcdad2612b2d37453aaeda297024dc4397db47f8f85bd0, SequenceNumber(1))\") } }", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 14 Feb 2022 02:03:23 GMT", "server-timing": "finish_request;dur=0", "access-control-allow-origin": "*", "x-sui-chain-id": "d1ca8c32", "x-sui-chain": "unknown", "x-sui-epoch": "0", "x-sui-checkpoint-height": "34", "x-sui-timestamp-ms": "1644804202802", "x-sui-timestamp": "2022-02-14T02:03:22.802Z", "x-sui-lowest-available-checkpoint": "0", "x-sui-lowest-available-checkpoint-objects": "34", "server": "sui-node/unknown", "vary": "origin, access-control-request-method, access-control-request-headers"} }, source: None }
```



---

## Release notes

Check each box that your changes affect. If none of the boxes relate to
your changes, release notes aren't required.

For each box you select, include information after the relevant heading
that describes the impact of your changes that a user might notice and
any actions they must take to implement updates.

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK: