[benchmarking] Enforce minimum committee size of 4
I was trying to get single-node network numbers by running with `--committee-size 1`, but this causes the crash below for any committee size less than 4. Enforce the minimum committee size to ensure others don't make the same mistake.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', sui/src/bench.rs:262:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:729:21
   4: bench::ClientServerBenchmark::make_structures
             at ./src/bench.rs:262:36
   5: bench::main
             at ./src/bench.rs:99:33
   6: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```