[graphql/rpc] add example validation and fix broken examples (#14444)
## Description 

Adds example validation logic to check correctness
Also fixes queries which the validator found to be broken


Sample error output

```
running 1 test
Starting server with config: ConnectionConfig { port: 8000, host: "127.0.0.1", db_url: "postgres://0.0.0.0:5432/postgres", prom_url: "0.0.0.0", prom_port: 9184 }
Starting Prometheus HTTP endpoint at 0.0.0.0:9184
Launch GraphiQL IDE at: http://127.0.0.1:8000
thread 'test::test_single_query_per_file' panicked at crates/sui-graphql-rpc/tests/examples_validation_tests.rs:112:9:

Query failed: transaction_block_kind at: crates/sui-graphql-rpc/examples/transaction_block/transaction_block_kind.graphql
[{"message":"Field \"objects\" must not have a selection since type \"SuiAddress\" has no subfields","locations":[{"line":26,"column":11}]},{"message":"Unknown field \"owner\" on type \"SuiAddress\".","locations":[{"line":27,"column":13}]}]

Query failed: paid_addr_filter at: crates/sui-graphql-rpc/examples/transaction_block_connection/paid_addr_filter.graphql
[{"message":"Internal error occurred while processing request: Paid address filter not supported","locations":[{"line":3,"column":3}],"path":["transactionBlockConnection"],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test::test_single_query_per_file ... FAILED

failures:
```


## Test Plan 

Existing, manual

---
If your changes are not user-facing and not a breaking change, you can
skip the following section. Otherwise, please indicate what changed, and
then add to the Release Notes section as highlighted during the release
process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade
binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes