Fix clippy warnings due to auto-deref (#23066)
## Description 

A typical warning looks like this:
```
error: deref which would be done by auto-deref
  --> sui-execution/latest/sui-move-natives/src/crypto/zklogin.rs:93:9
   |
93 |         &*audience.as_bytes_ref(),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `&audience.as_bytes_ref()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
```

This is currently failing in CI e.g.,
https://github.com/MystenLabs/sui/actions/runs/16843368393/job/47718719732?pr=22893

## Test plan 
```
cargo xclippy -D warnings
```
---

## Release notes

Check each box that your changes affect. If none of the boxes relate to
your changes, release notes aren't required.

For each box you select, include information after the relevant heading
that describes the impact of your changes that a user might notice and
any actions they must take to implement updates.

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK: